#!/bin/sh 

# /home/jason/jvms/jdk1.6.0_18

nvcc -O3 -Xcompiler -fPIC --include-path /usr/local/cuda-sdk/common/inc -c scale-gpu.cu -o scale-gpu.o
gcc -fPIC -O3 -shared -I/home/jason/jvms/jdk1.6.0_18/include -I/home/jason/jvms/jdk1.6.0_18/include/linux -I../../../build/headers -I/usr/local/cuda/include -I/usr/local/cuda-sdk/common/inc/ -c scale-jni.c -o scale-jni.o
gcc -fPIC -shared -L/usr/local/cuda/lib scale-gpu.o scale-jni.o -o libSIMPLE_CUDA_SCALER-Linux-amd64.so -lcudart
mv libSIMPLE_CUDA_SCALER-Linux-amd64.so ../../..
