#!/bin/bash

CLUSTER=$1
shift

DELAY=$1
shift

SIZE=$1
shift

POOL=$1
shift

java -cp "./external/*:./build-eclipse:.:" -Dibis.cohort.steal.delay=$DELAY -Dibis.cohort.steal.size=$SIZE -Dibis.pool.name=$POOL -Dibis.server.address=localhost:12345 -Dibis.cohort.impl=dist+mt+st:$CLUSTER datachallenge.simple.Main -cluster $CLUSTER -dataDir /home/jason/test-data-challenge/$CLUSTER -execDir `pwd` -tmpDir /home/jason/test-data-challenge/tmp/$CLUSTER $@ -clusters cluster1 cluster2 cluster3 cluster4   

